# Generated by Django 5.1.11 on 2025-08-11 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fee_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of Rental Amount'), ('FIXED_PER_DAY', 'Fixed Amount Per Day'), ('FIXED_PER_HOUR', 'Fixed Amount Per Hour')], max_length=20)),
                ('fee_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount based on fee type', max_digits=10)),
                ('grace_period_hours', models.PositiveIntegerField(default=0, help_text='Grace period in hours before late fees apply')),
                ('max_fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum late fee amount (optional)', max_digits=10, null=True)),
                ('max_fee_days', models.PositiveIntegerField(blank=True, help_text='Maximum days to charge late fees (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_rules', to='catalog.productcategory')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_rules', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Late Fee Rule',
                'verbose_name_plural': 'Late Fee Rules',
                'db_table': 'late_fee_rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to='accounts.customergroup')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
                'db_table': 'price_lists',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('rate_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Price per hour', max_digits=10, null=True)),
                ('rate_day', models.DecimalField(blank=True, decimal_places=2, help_text='Price per day', max_digits=10, null=True)),
                ('rate_week', models.DecimalField(blank=True, decimal_places=2, help_text='Price per week', max_digits=10, null=True)),
                ('rate_month', models.DecimalField(blank=True, decimal_places=2, help_text='Price per month', max_digits=10, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED', 'Fixed Amount Discount')], max_length=20, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=10, null=True)),
                ('min_duration_hours', models.PositiveIntegerField(default=0, help_text='Minimum rental duration in hours for this rule to apply')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Minimum quantity for this rule to apply')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='catalog.productcategory')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.pricelist')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Price Rule',
                'verbose_name_plural': 'Price Rules',
                'db_table': 'price_rules',
                'ordering': ['-min_duration_hours', '-min_quantity'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='price_rules_product_a6bc44_idx'), models.Index(fields=['category', 'is_active'], name='price_rules_categor_a3102d_idx'), models.Index(fields=['price_list', 'is_active'], name='price_rules_price_l_3079f7_idx')],
            },
        ),
    ]
