# Generated by Django 5.1.11 on 2025-08-11 09:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=64, unique=True)),
                ('document_type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], default='PICKUP', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('vehicle', models.CharField(blank=True, max_length=100)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('customer_contact', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer_signature', models.TextField(blank=True)),
                ('driver_signature', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_documents', to='orders.reservation')),
            ],
            options={
                'verbose_name': 'Delivery Document',
                'verbose_name_plural': 'Delivery Documents',
                'db_table': 'delivery_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_scheduled', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_delivered', models.PositiveIntegerField(default=0)),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('condition_at_pickup', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('condition_at_return', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], max_length=20)),
                ('serial_numbers', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('damage_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.deliverydocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Delivery Item',
                'verbose_name_plural': 'Delivery Items',
                'db_table': 'delivery_items',
            },
        ),
        migrations.CreateModel(
            name='ReturnDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Return'), ('SCHEDULED', 'Return Scheduled'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Return Completed'), ('PARTIAL', 'Partial Return'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('vehicle', models.CharField(blank=True, max_length=100)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('due_datetime', models.DateTimeField()),
                ('pickup_address', models.TextField()),
                ('return_address', models.TextField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('late_fee_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_instructions', models.TextField(blank=True)),
                ('customer_contact', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('customer_signature', models.TextField(blank=True)),
                ('driver_signature', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_returns', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_documents', to='orders.reservation')),
            ],
            options={
                'verbose_name': 'Return Document',
                'verbose_name_plural': 'Return Documents',
                'db_table': 'return_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
                ('route_date', models.DateField()),
                ('vehicle', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=15)),
                ('start_location', models.TextField()),
                ('end_location', models.TextField()),
                ('estimated_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('planned_start_time', models.TimeField()),
                ('actual_start_time', models.TimeField(blank=True, null=True)),
                ('planned_end_time', models.TimeField()),
                ('actual_end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_documents', models.ManyToManyField(blank=True, to='deliveries.deliverydocument')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_routes', to=settings.AUTH_USER_MODEL)),
                ('return_documents', models.ManyToManyField(blank=True, to='deliveries.returndocument')),
            ],
            options={
                'verbose_name': 'Delivery Route',
                'verbose_name_plural': 'Delivery Routes',
                'db_table': 'delivery_routes',
                'ordering': ['-route_date', '-planned_start_time'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_due', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('quantity_missing', models.PositiveIntegerField(default=0)),
                ('quantity_damaged', models.PositiveIntegerField(default=0)),
                ('condition_returned', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged'), ('missing', 'Missing')], default='good', max_length=20)),
                ('serial_numbers_returned', models.JSONField(blank=True, default=list)),
                ('serial_numbers_missing', models.JSONField(blank=True, default=list)),
                ('serial_numbers_damaged', models.JSONField(blank=True, default=list)),
                ('damage_description', models.TextField(blank=True)),
                ('damage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('replacement_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('return_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.returndocument')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'db_table': 'return_items',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_number', models.CharField(max_length=64, unique=True)),
                ('movement_type', models.CharField(choices=[('PICKUP', 'Pickup from Stock'), ('RETURN', 'Return to Stock'), ('DAMAGE', 'Damage Adjustment'), ('LOSS', 'Loss Adjustment'), ('MAINTENANCE', 'Maintenance')], max_length=15)),
                ('quantity', models.IntegerField()),
                ('from_location', models.CharField(blank=True, max_length=100)),
                ('to_location', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('cost_impact', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.deliverydocument')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('return_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.returndocument')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverydocument',
            index=models.Index(fields=['driver', 'status'], name='delivery_do_driver__319b03_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverydocument',
            index=models.Index(fields=['status', 'scheduled_datetime'], name='delivery_do_status_65e8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverydocument',
            index=models.Index(fields=['document_number'], name='delivery_do_documen_2523b4_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverydocument',
            index=models.Index(fields=['reservation', 'document_type'], name='delivery_do_reserva_1dc8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryitem',
            index=models.Index(fields=['delivery_document', 'product'], name='delivery_it_deliver_380d45_idx'),
        ),
        migrations.AddIndex(
            model_name='returndocument',
            index=models.Index(fields=['driver', 'status'], name='return_docu_driver__4bd36b_idx'),
        ),
        migrations.AddIndex(
            model_name='returndocument',
            index=models.Index(fields=['status', 'due_datetime'], name='return_docu_status_8a52ce_idx'),
        ),
        migrations.AddIndex(
            model_name='returndocument',
            index=models.Index(fields=['document_number'], name='return_docu_documen_b0f957_idx'),
        ),
        migrations.AddIndex(
            model_name='returndocument',
            index=models.Index(fields=['reservation'], name='return_docu_reserva_539c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryroute',
            index=models.Index(fields=['driver', 'route_date'], name='delivery_ro_driver__deef29_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryroute',
            index=models.Index(fields=['status', 'route_date'], name='delivery_ro_status_b302e8_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['return_document', 'product'], name='return_item_return__d99d52_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'movement_type'], name='stock_movem_product_1c9b03_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='stock_movem_created_07bdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_number'], name='stock_movem_movemen_58e1d7_idx'),
        ),
    ]
