# Generated by Django 4.2.23 on 2025-08-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default daily rental rate (can be overridden by pricing rules)', max_digits=10, null=True),
        ),
    ]
